<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
<!ELEMENT students (student | course)*>
<!ELEMENT student EMPTY>
<!ATTLIST student sid ID #REQUIRED>
<!ATTLIST student sname CDATA #REQUIRED>
<!ATTLIST student smob CDATA #REQUIRED>
<!ELEMENT course EMPTY>
<!ATTLIST course cid ID #REQUIRED>
<!ATTLIST course cname CDATA #REQUIRED>
<!ATTLIST course scid IDREF #REQUIRED>
]>

<students>
	<student sid="s1" sname="rajesh" smob="94949"></student>
	<student sid="s2" sname="akshith" smob="9595"></student>
	<student sid="s3" sname="vignesh" smob="969696"></student>

	<course cid="c1" cname="JAVA" scid="s1"></course>
	<course cid="c2" cname="PYTHON" scid="s2"></course>
	<course cid="c3" cname="PHP" scid="s3"></course>
</students>